name: Commit a version change
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-major-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@c8d6ab30f745aab1b49da751e9b020cbe73779ce # v9.0.0
    with:
      version-type: major
      create-feature-docs: true
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}

  check-minor-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@c8d6ab30f745aab1b49da751e9b020cbe73779ce # v9.0.0
    with:
      version-type: minor
      create-feature-docs: true
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}

  check-patch-version:
    permissions:
      contents: write
      pull-requests: write
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@c8d6ab30f745aab1b49da751e9b020cbe73779ce # v9.0.0
    with:
      version-type: patch
      create-feature-docs: true
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY}}
