name: Create feature docs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-docs:
    uses: alextheman231/github-actions/.github/workflows/create-feature-docs.yml@f07e4455c803bbc180ba3525684b943a9e32e613 # v9.0.1
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
