name: Create feature docs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-docs:
    uses: alextheman231/github-actions/.github/workflows/create-feature-docs.yml@c8d6ab30f745aab1b49da751e9b020cbe73779ce # v9.0.0
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
